feat: add Symfony 6 support
sonata-project/SonataIntlBundle pull request #475
Opened 2021-10-21 21:41 UTC by Kocal

## Subject

I am targeting this branch, because it does not contain BC.

Part of: https://github.com/sonata-project/dev-kit/issues/1675
Dev-kit PR: https://github.com/sonata-project/dev-kit/pull/1733

## Changelog

```markdown
### Added
- Added some Symfony 6 support
```

2021-10-21 21:46 UTC, Kocal commented on tests/Timezone/UserBasedTimezoneDetectorTest.php
> +            }
This is needed because `TokenInterface#getUser()` will be typed to `?UserInterface`, and `$user` was not implementing this interface.

2021-10-21 21:52 UTC, jordisala1991 commented on src/Resources/config/intl.xml
> +            <deprecated package="sonata-project/intl-bundle" version="2.8">The "%service_id%" service is deprecated since sonata-project/intl-bundle 2.8 and will be removed in 3.0.</deprecated>
I think this needs to be converted to php format and solved with a bc layer like we did on SonataAdminBundle 3.x

2021-10-21 21:52 UTC, jordisala1991 commented on src/Resources/config/intl.xml
> +            <deprecated package="sonata-project/intl-bundle" version="2.8">The "%service_id%" service is deprecated since sonata-project/intl-bundle 2.8 and will be removed in 3.0.</deprecated>
Probably another Pr to do so would be nice

2021-10-21 21:54 UTC, jordisala1991 commented on src/DependencyInjection/Configuration.php
> +    public function getConfigTreeBuilder(): TreeBuilder
isnt this a bc break?

2021-10-21 21:55 UTC, Kocal commented on src/Resources/config/intl.xml
> +            <deprecated package="sonata-project/intl-bundle" version="2.8">The "%service_id%" service is deprecated since sonata-project/intl-bundle 2.8 and will be removed in 3.0.</deprecated>
I planned to drop Symfony 4 support (and so get ride of the error messages) when I saw the CI fails.

I will check what has been done on SonataAdminBundle. Should I keep this PR _clean_ or open a new PR for the BC layer?

2021-10-21 21:56 UTC, jordisala1991 commented on src/Resources/config/intl.xml
> +            <deprecated package="sonata-project/intl-bundle" version="2.8">The "%service_id%" service is deprecated since sonata-project/intl-bundle 2.8 and will be removed in 3.0.</deprecated>
I would prefer that if you dont mind

2021-10-21 21:58 UTC, jordisala1991 commented on src/Resources/config/intl.xml
> +            <deprecated package="sonata-project/intl-bundle" version="2.8">The "%service_id%" service is deprecated since sonata-project/intl-bundle 2.8 and will be removed in 3.0.</deprecated>
Here you have the example: https://github.com/sonata-project/SonataAdminBundle/blob/169e31691978822a00a82333e2f52f15b4abc049/src/Resources/config/commands.php#L37

I would suggest adding the same Bc layer class here and use it on the php version of this file

2021-10-21 21:59 UTC, Kocal commented on src/DependencyInjection/Configuration.php
> +    public function getConfigTreeBuilder(): TreeBuilder
I'm not sure, the `@return` tag is present since [Symfony 4.4](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Config/Definition/ConfigurationInterface.php#L24) and is still there in [Symfony 5.4](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Config/Definition/ConfigurationInterface.php#L26).

The native return type has not been added in [Symfony 6](https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/Config/Definition/ConfigurationInterface.php#L26) but it's a matter of time IMO, but I may be wrong.

2021-10-21 22:01 UTC, Kocal commented on src/Resources/config/intl.xml
> +            <deprecated package="sonata-project/intl-bundle" version="2.8">The "%service_id%" service is deprecated since sonata-project/intl-bundle 2.8 and will be removed in 3.0.</deprecated>
Alright, gonna open a new PR once this one is merged!

2021-10-21 22:03 UTC, jordisala1991 commented on src/DependencyInjection/Configuration.php
> +    public function getConfigTreeBuilder(): TreeBuilder
If it is not added it wont be added, I confirmed that on the main issue for sf 6 on its repository. For this one we should remove the inherit comment and add the return phpdoc to avoid deprecation

2021-10-21 22:05 UTC, jordisala1991 commented on src/Resources/config/intl.xml
> +            <deprecated package="sonata-project/intl-bundle" version="2.8">The "%service_id%" service is deprecated since sonata-project/intl-bundle 2.8 and will be removed in 3.0.</deprecated>
I dont think is possible this pr passes the validation for sf 4.4 without that bc layer

2021-10-21 22:51 UTC, Kocal commented on src/Resources/config/intl.xml
> +            <deprecated package="sonata-project/intl-bundle" version="2.8">The "%service_id%" service is deprecated since sonata-project/intl-bundle 2.8 and will be removed in 3.0.</deprecated>
Configuration files have been migrated to PHP.

2021-10-22 05:49 UTC, jordisala1991 commented on src/Twig/Extension/NumberExtension.php
> +    public function getFilters(): array
This shouldnt be needed either (also bc break) , it should be instead as phpdoc

2021-10-22 05:49 UTC, jordisala1991 commented on src/Templating/Helper/DateTimeHelper.php
> +    public function getName(): string
can you move those to phpdoc?

2021-10-22 05:50 UTC, jordisala1991 commented on src/Resources/config/autowire.php
> +    // Use "param" function for creating references to parameters when dropping support for Symfony 5.1
those 2 comment are not needed on this specific file

2021-10-22 05:54 UTC, core23 commented on src/Templating/Helper/DateTimeHelper.php
> +    public function getName(): string
Adding type hints to an non-final class is a BC break, so it can't be done on a stable branch.

That's why we use PHPDoc for this

2021-10-22 07:23 UTC, Kocal commented
Hi everyone, review comments have been addressed.

Thanks!

2021-10-22 07:23 UTC, jordisala1991 commented on composer.json
> +    "minimum-stability": "dev"
this change should be reverted, it is already handled via github actions

2021-10-22 07:24 UTC, jordisala1991 commented
> Hi everyone, review comments have been addressed.
> 
> Thanks!

Nice, Thank you for your time! Just a minor comment and I think we are ready to get some more reviews. Also, make sure you pass all the CI checks

2021-10-22 08:15 UTC, Kocal commented on composer.json
> +    "minimum-stability": "dev"
Yeah my bad, sorry!

2021-10-22 08:16 UTC, Kocal commented
Done :grimacing:

2021-10-22 08:24 UTC, jordisala1991 commented
> Done 😬

Php-cs-fixer is still failing

2021-10-22 08:33 UTC, Kocal commented
I've installed php-cs-fixer globally, it should be okay now.

Sorry for the waste of time :grimacing:

2021-10-22 08:42 UTC, jordisala1991 commented
> I've installed php-cs-fixer globally, it should be okay now.
> 
> Sorry for the waste of time 😬

Looks good now :)

2021-10-22 08:46 UTC, core23 submitted a review, later dismissed

2021-10-22 09:52 UTC, franmomu submitted a review, later dismissed

2021-10-22 10:05 UTC, jordisala1991 commented on src/Resources/config/intl.xml
> -        <service id="sonata.intl.twig.extension.datetime" class="%sonata.intl.twig.helper.datetime.class%" public="false">
this is marked as public=false, can you take a look at the public() you used on the php file?

2021-10-22 10:06 UTC, jordisala1991 requested changes
Probably the php file for service definition needs some adjustments

2021-10-22 10:12 UTC, Kocal commented on src/Resources/config/intl.xml
> -        <service id="sonata.intl.twig.extension.datetime" class="%sonata.intl.twig.helper.datetime.class%" public="false">
Fixed, thanks!

2021-10-22 12:24 UTC, jordisala1991 approved these changes

2021-10-22 12:26 UTC, franmomu approved these changes

2021-10-22 12:35 UTC, merged

2021-10-22 12:35 UTC, jordisala1991 commented
Thanks @Kocal